# argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: attendance-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akhileshmishrabiz/student-portal.git
    targetRevision: HEAD
    path: k8s/exercise4/  # Directory containing your K8s manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true